### ISSUE TITLE
中文能看的明白吗？

### ISSUE THREAD

**Issue by y112102** [castle-it/dynamic-linq-query-builder#17]
中文能看的明白吗？ 我有个问题 。

**Comment by tghamm** [comment]
I don't understand Chinese unfortunately. But if you have a question in English I'm happy to try and answer.

**Comment by y112102** [comment]
How to use dynamic linq query builder with SQL？
c# code =>


![12](https://user-images.githubusercontent.com/8541201/26859530-001b2ea8-4b6b-11e7-9edf-18c961384377.png)

**Comment by y112102** [comment]
I know my English is poor, so I hope you to help me

**Comment by y112102** [comment]
QueryBuilder.cs  Folder 
![34](https://user-images.githubusercontent.com/8541201/26859618-9b220732-4b6b-11e7-9d11-02803b7aa3af.png)

**Comment by quakedc** [comment]
Hi y112102,

You need to get the rules of the query from QueryBuilder (e.g. queryBuilder('getRules')). Then you need to create an API in your code to get those rules and deserialize into a FilterRule object. Finally, you need to call the BuildQuery method with the specified filter rules .

It'll be much easier if you download the example and run through it.

**Comment by elvira1989** [comment]
just add this script to the index script:
      $('#btn-get-sql').on('click', function() {
            var target = $(this).data('target');
            var result = jqueryQueryBuilder.queryBuilder('getSQL', false, true);
            if (!$.isEmptyObject(result)) {
               alert(result.sql);
            }           
            }
and of course  add this button to the index html
        <button id="btn-get-sql">SQL</button>
works like a charm :-)
