### ISSUE TITLE
Adding Support to .Net Core 2 and .Net Standard

### ISSUE THREAD

**Issue by PolaEdward** [castle-it/dynamic-linq-query-builder#18]
It would be great if .Net Core and .Net Standard is supported.
The following could be useful.
https://github.com/StefH/System.Linq.Dynamic.Core

**Comment by Misiu** [comment]
@tghamm after initial tests Your solution works fine in .NET Core 2.1 with Entity Framework 2.1. I've copy/pased QueryBuilder clas to my solution and it just works 😃 

I've noticed one thing with the generated query.
If I have this filter:
```
{
    "condition": "or",
    "value": 1,
    "rules": [
        {
            "field": "userId",
            "operator": "equal",
            "type": "integer",
            "value":3106
        },
        {
            "field": "phoneNumberTokenFailedCount",
            "operator": "equal",
            "value": 0,
            "type": "integer"
        }
    ]
}
```

and this C# code:
`var data = await _context.WsUser.BuildQuery(filterRule).Take(10).ToListAsync();`

this gets translated to this SQL query:
```
SELECT TOP (@__p_0) [item].[UserID], 
                    [item].[PhoneNumberTokenFailedCount], 
                    [item].[UserName]
FROM [WS_User] AS [item]
WHERE(CASE
          WHEN [item].[UserID] = 3106
          THEN CAST(1 AS BIT)
          ELSE CAST(0 AS BIT)
      END|CASE
              WHEN [item].[PhoneNumberTokenFailedCount] = 0
              THEN CAST(1 AS BIT)
              ELSE CAST(0 AS BIT)
          END) = 1;
```

when I create LINQ query by hand:
`var data = await _context.WsUser.Where(u => u.UserId == 3106 || u.PhoneNumberTokenFailedCount == 0).Take(10).ToListAsync();`
it gets translated to this SQL query:

```
SELECT TOP (@__p_0) [u].[UserID], 
                    [u].[PhoneNumberTokenFailedCount], 
                    [u].[UserName]
FROM [WS_User] AS [u]
WHERE([u].[UserID] = 3106)
     OR ([u].[PhoneNumberTokenFailedCount] = 0);
```

Notice the difference is this simple query. I'll create more complex queries and will get back with results.

**Comment by tghamm** [comment]
@Misiu so it's not a top priority for us as we don't have anything on Core just yet, however, I aim to look at supporting it within the next 2-4 months assuming the changes are more on the trivial side than the complete re-write side.

**Comment by tghamm** [comment]
@Misiu off hand I'm not sure why the query would be more complex, however, it's worth noting when we designed this, it was designed to be used against in-memory collections, so I can't guarantee the expression trees generated by this library are optimized the way a native linq query might be.

**Comment by Misiu** [comment]
@tghamm thanks for reply :) Today I've done some more tests with more complex queries and everything works fine.
I'm creating a similar extension that will allow dynamically selecting properties (columns) so that You will be able to specify which columns You want from DB. This also uses expressions so I'll take another look at Your library and expression trees. If I find something I'll let You know.

BTW awesome library 👍

**Comment by tghamm** [comment]
@PolaEdward @Misiu a new release has been published, and we now support .NET 4.5 and .NET Standard 2.0.  Hope it helps.  Thanks!
