### ISSUE TITLE
Datepiker is not working

### ISSUE THREAD

**Issue by elvira1989** [castle-it/dynamic-linq-query-builder#21]
hi i tried to use date piker or other widget such as slider and it is not working can you help with an example? 
  ooo and thanks for the .net example you are a life savior !

**Comment by tghamm** [comment]
hi @elvira1989 I'm sorry for the slow response here, but I've added a basic example to use the datepicker in the samples project.  The convenience methods to generate the definition for a given type don't support every option, so I'd suggest you construct that manually in JS per the jquery-query-builder docs, but the backend library should support it without issue.
