### ISSUE TITLE
Non-Static PersonBuilder.GetPeople()

### ISSUE THREAD

**Issue by popacorp** [castle-it/dynamic-linq-query-builder#27]
Hi,

I would like to query data from a database instead of using the TestData provided. The problem I am facing is that the PersonBuilder Class is Static and it's not allowing me to open a dbcontext inside the class. If I modify PersonBuilder to be non-static I get the following error in the HomeController:

> CS0120: An object reference is required for the nonstatic field, method, or property 'member'

At the following line:

`var people = PersonBuilder.GetPeople().BuildQuery(obj).ToList();`

**Comment by tghamm** [comment]
I would think you'd need to call an instantiated `PersonBuilder` class then.

`var pBuilder = new PersonBuilder();`
`var people = pBuilder.GetPeople().BuildQuery(obj).ToList();`
