### ISSUE TITLE
Question: FilterRule for complex types 

### ISSUE THREAD

**Issue by MasallahOZEN** [castle-it/dynamic-linq-query-builder#37]
Hi guys, thanks for writing this library. Can you help me about complex type?  How can I generate rule for  PersonRecord.Address ?

public class PersonRecord
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public DateTime Birthday { get; set; }
        public Address Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }

    }

    public class Address
    {
        public string Name { get; set; }
        public string Location { get; set; }
    }

Best Regards,
Maşallah ÖZEN

**Comment by MasallahOZEN** [comment]
Fix with Release 1.1.2

Thnx

**Comment by tghamm** [comment]
You're welcome!  Hope it helps.

**Comment by MasallahOZEN** [comment]
Thnx, I couldnt see your email, so I had to write from here. Can you help me please ? 

Detail info :
https://groups.google.com/forum/#!topic/appccelerate/7SGKs-RxhYY

Thnx so much,
