### ISSUE TITLE
dd/mm/yyyy date format

### ISSUE THREAD

**Issue by tyronent** [castle-it/dynamic-linq-query-builder#43]
BuildExpressionOptions.CultureInfo is read only...I need to parse dates in dd/mm/yyyy format but since CultureInfo can't be changed I am getting a System.FormatException.

Is there some work around this?

tnx

**Comment by tghamm** [comment]
@tyronent simple oversight on our part.  I've added a setter in the working branch, should be released today or tomorrow.

**Comment by tyronent** [comment]
@tghamm great tnx

**Comment by tghamm** [comment]
@tyronent new release is out and addresses this issue.
