### ISSUE TITLE
NestedObjects - GenericList

### ISSUE THREAD

**Issue by MasallahOZEN** [castle-it/dynamic-linq-query-builder#45]
Hi, how can filter nested object with generic list?
Exm: 

Data:
- User.Profile[0].Code = "Name"
- User.Profile[1].Code = "Surname"
- User.Profile[2].Code = "Gender"

Filter:
- Field: "User.Profile.Code" - Operator: equal- Value: Name
- AND Field: "User.Profile.Value" - Operator: containes- Value: FirstName

Thnx

**Comment by MasallahOZEN** [comment]
@tghamm thnx for your response. Yes, I'm interested in adding it myself. I will share the result as soon as possible.

**Comment by tghamm** [comment]
@MasallahOZEN cool, that'd be helpful.  Below is the link to the fork where someone did some of the work.  We've made several changes/enhancements since then, so it wouldn't be as simple as merging the code, but it may give you some ideas on where to start.

[https://github.com/LeoYReyes/dynamic-linq-query-builder](https://github.com/LeoYReyes/dynamic-linq-query-builder)

**Comment by MasallahOZEN** [comment]
Hi thnx for your response. But there is a problem. Nested collections work only for any, not work for filtered select.  I want to filter nested collection with dynamic query. At the below, I figured my object and datas. 

When rule executed, the result must have 
- rootObj.ChildObj with ID = 1075
-----and Data item count = 2 (Only ID 1 and 2)

Sorry for my English :(

Thnx everyone.


DEFINITIONS
=========================
RootObj
-int ID
- List<ChildObject> ChildObj

ChildObject
- ID
- List<ChildObjectData> Data

ChildObjectData
- ID
- Code


QUERY
=======================
{
	"Condition": "AND",
	"Rules": [{
			"Condition": "AND",
			"Field": "ID",
			"Id": "ID",
			"Input": "text",
			"Operator": "equal",
			"Type": "integer",
			"Value": 1
		}, {
			"Condition": "AND",
			"Field": "ChildObj.ID",
			"Id": "ChildObj.ID",
			"Input": "text",
			"Operator": "equal",
			"Type": "integer",
			"Value": 1075
		}, {
			"Condition": "AND",
			"Field": "ChildObj.Data.Code",
			"Id": "ChildObj.ID",
			"Input": "text",
			"Operator": "int",
			"Type": "integer",
			"Value": "CODE1,CODE2"
		}
	]
}


DATA
=====================
var rootObj = new RootObj();
rootObj.ID = 1;
rootObj.ChildObj = new List<ChildObject>(){

						new ChildObject(){
							ID = 1074,
							Data = new List<ChildObjectData>(){
								new ChildObjectData(){
									ID = 1,
									Code = "CODE1"
								}
							}
						},
						new ChildObject(){
							ID = 1075,
							Data = new List<ChildObjectData>(){
								new ChildObjectData(){
									ID = 1,
									Code = "CODE1"
								},
								new ChildObjectData(){
									ID = 2,
									Code = "CODE2"
								},
								new ChildObjectData(){
									ID = 3,
									Code = "CODE3"
								}
							}
						}
					};

**Comment by clegoz** [comment]
I'm afraid you cannot filter child collections like that. It's impossible even with pure LINQ. What you're asking is equivalent to: `source.Where(s => s.Data.Where(c => c.Code == 'CODE1'))` which cannot be compiled.

You have to filter the child collections first and then you have to create new root collection. LINQ equivalent: `source.Select(s => new ChildObject() { Data = s.Data.Where(c => c.Code == 'CODE1') })`

**Comment by MasallahOZEN** [comment]
Thnx for your response, that's right. But I solved with another way. I'm doing two way filter; first filtering root object and after get child prop list and execute filter on it.

![image](https://user-images.githubusercontent.com/811777/57061632-48aafa80-6cc6-11e9-8427-5b168cb3729e.png)
