### ISSUE TITLE
Is it possible to filter over related data?

### ISSUE THREAD

**Issue by CrestApps** [castle-it/dynamic-linq-query-builder#47]
First of all, thank you for this great package! Your time and effort are much appreciated. 

I am wondering if there is a way to control which related dataset should the filter get applied to. Here is an example which used Entity Framework

```
// Course Entry
public class Course
{
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int TeacherId { get; set; }

        public virtual User Teacher { get; set; }
        public virtual ICollection<User> Students { get; set; }
        public virtual ICollection<Course> RelatedCourses { get; set; }
        public virtual ICollection<Course> PreRequisites { get; set; }
}
```

Now, I want to query the `Courses` and filter by the related data (aka virtual properties). The incoming filters will look something like this 

```
var contentIdFilter = new QueryBuilderFilterRule()
{
    Condition = "or",
    Rules = new List<QueryBuilderFilterRule>()
    {
        new QueryBuilderFilterRule()
        {
            Condition = "and",
            Field = "Course Name",
            Id = "Code",
            Input = "text",
            Operator = "equal",
            Type = "string",
            Value = "C# 101",
            Rules = new List<QueryBuilderFilterRule>()
            {
                Condition = "and",
                new QueryBuilderFilterRule()
                {
                    Condition = "and",
                    Field = "Teacher's First Name",
                    Id = "course.Teacher.FirstName",
                    Input = "text",
                    Operator = "equal",
                    Type = "string",
                    Value = "F.Name"
                },
                new QueryBuilderFilterRule()
                {
                    Condition = "and",
                    Field = "Teacher's Last Name",
                    Id = "course.Teacher.LastName",
                    Input = "NA",
                    Operator = "equal",
                    Type = "Text",
                    Value = "L.Name"
                }
            }
        },
        new QueryBuilderFilterRule()
        {
            Condition = "and",
            Field = "Related Courses' Code",
            Id = "RelatedCoursesCode",
            Input = "text",
            Operator = "equal",
            Type = "string",
            Value = "C# 101",
        }
    }
};
```

Then the LINQ statement would look something like this

```
DataContext.Courses.Where(course => course.Code == "C# 101" || (course.Teacher.FirstName == "F.Name" && course.Teacher.LastName == "L.Name") || course.RelatedCourses .Contains(relatedCourse  => relatedCourse.Code == "C# 101")).ToList();
```

I am not sure if the package is flexible enough to allow me to do such a logic. But in theory, if there was a way to set the expression source in the `QueryBuilderFilterRule` class, it should be doable. Of course, I could be oversimplifying it here but would be very helpful if there is a way to filter by related data.

I could be completely wrong here, but could we change the following line

```
var pe = Expression.Parameter(typeof(T), "item");
```

to 

```
string alias = "item";

if(!string.IsNullOrWhiteSpace(filterRule.Alias)) 
{
    alias = filterRule.Alias.Trim();
}

var pe = Expression.Parameter(typeof(T), alias);
```

Then we would add `string Alias { get; }` to the `IFilterRule` contract.

Thank you in advance for your help here.

**Comment by tghamm** [comment]
Hi, so we halfway support what you're looking for right now, and we have a PR under review to support the collections.  Basically right now we can handle nested virtual properties, but not collections.  So `Course.Teacher.FirstName` should work just fine, but your `RelatedCourses query would not work until our next release.  See issue #45 for the discussion on supporting collections.  We'll likely roll that out in the next couple of weeks.

**Comment by CrestApps** [comment]
That's is great news! Can't wait for the next release. Thank you.
