### ISSUE TITLE
Can I use Dictionary prop and filter on keys ?

### ISSUE THREAD

**Issue by MasallahOZEN** [castle-it/dynamic-linq-query-builder#48]
Hi, can I use Dictionary prop and filter on keys ? I'll use it for dynamic props.

**Comment by tghamm** [comment]
@MasallahOZEN not currently, no.  There's not a terribly simple way to implement that without duplicating most of the methods as they are all currently property based.  It's something we might consider supporting long-term, but it's not a common use case presently.
