### ISSUE TITLE
FilterRule Value is null when json is array

### ISSUE THREAD

**Issue by clongo7** [castle-it/dynamic-linq-query-builder#7]
In the sample when I use the between operator on the query builder, the values object of that rule contains a JSON array. When I post this to the server, the value is null.

![image](https://cloud.githubusercontent.com/assets/20171634/16389131/b4985ce2-3c59-11e6-9834-6931e806bec2.png)

![image](https://cloud.githubusercontent.com/assets/20171634/16389162/d684bf8a-3c59-11e6-99d5-06d09d86d15f.png)

**Comment by tghamm** [comment]
@clongo7, thanks for the report, we'll take a look as soon as possible and report back.

**Comment by tghamm** [comment]
@clongo7 I've committed a change to the sample at:
[`Link to sample source change`](https://github.com/castle-it/dynamic-linq-query-builder/blob/48f3051d6c4cae899968783cfade99d4b8b22319/Castle.DynamicLinqQueryBuilder.Samples/Views/Home/Index.cshtml#L33-L57)

It's in the 1.0.5 branch for the moment but I'll likely merge to master over the weekend.

Basically you need to convert the javascript array into a comma delimited string.  We may change that to a server-side fix at some point in the future, but this ought to get you going for now.

**Comment by tghamm** [comment]
I've merged the fix into master.  Thanks again for bringing this to our attention.

**Comment by clongo7** [comment]
Thank you for the code. This is a great plugin!
