### ISSUE TITLE
How to use dynamic linq query builder with SQL

### ISSUE THREAD

**Issue by vickyrathee** [castle-it/dynamic-linq-query-builder#9]
I'm looking to utilize your package for dynamic filter to create reports for our application users. On the front end we are using JqueryQueryBuilder which generates the filter in JSON like this and then that JSON is sent using HTTP POST.

**Example JSON**
```
{
 "condition": "AND",
 "rules": [
   {
     "id": "price",
     "field": "price",
     "type": "double",
     "input": "text",
     "operator": "less",
     "value": "10.25"
   },
   {
     "condition": "OR",
     "rules": [
       {
         "id": "category",
         "field": "category",
         "type": "integer",
         "input": "select",
         "operator": "equal",
         "value": "2"
       },
       {
         "id": "category",
         "field": "category",
         "type": "integer",
         "input": "select",
         "operator": "equal",
         "value": "1"
       }]
   }]
}
```

Then here is my SQL

```
public Products GetProductById(object filterObj)  
 {  
     SqlDataReader reader = null;  
     SqlConnection myConnection = new SqlConnection();  
     myConnection.ConnectionString = @"Server=.\SQLSERVER2008R2;Database=DBCompany;User ID=sa;Password=xyz@1234;";  

     SqlCommand sqlCmd = new SqlCommand();  
     sqlCmd.CommandType = CommandType.Text;  
     sqlCmd.CommandText = "SELECT * FROM MYTABLE WHERE PRICE < 10.25 AND (CATEGORY = 2 OR CATEGORY = 1);  
     sqlCmd.Connection = myConnection;  
     myConnection.Open();  
     reader = sqlCmd.ExecuteReader();  
     Products prod = null;  
     while (reader.Read())  
     {  
         prod = new Products ();  
         prod.Id = Convert.ToInt32(reader.GetValue(0));  
         prod.Name = reader.GetValue(1).ToString();  
         prod.CategoryId = Convert.ToInt32(reader.GetValue(2));  
     }  
     return prod ;  

 }  
```

Is there a way i can use this pacakge to convert querybuilder filter object into SQL parameters ?

**Comment by tghamm** [comment]
Thanks for your interest!

Ok, so in your case, there are a couple of options.

The first is the SQL plugin for jQuery-QueryBuilder, and is probably the most direct solution to your problem.  It will generate a valid SQL WHERE clause based on the filters.  Given that you're using ADO.Net with handwritten queries, this should match up and be usable very easily.
Take a look at: [http://querybuilder.js.org/plugins.html](http://querybuilder.js.org/plugins.html)
In this scenario you wouldn't need our package at all.

The second option would be to use an ORM like Entity Framework to access your SQL data.  Using Linq to SQL or Entities to SQL, you could use our package to build the expression tree that is then converted to SQL by the ORM natively.  My guess is if you're not already using an ORM like EF, you aren't likely to want to add that to the mix, but this would be one possible way to go.

Hope this helps, let us know if we can answer any more questions.

**Comment by vickyrathee** [comment]
Generating SQL conditions on client side using plugin exposes a lots of thing to end users and also not safe for SQL injections.

Isn't any class in your package which can convert the JSON into SQL parameter with value? or any example/documentation to start with migrating our application on ORM like entity framework?

**Comment by tghamm** [comment]
That's certainly true, and part of the reason we don't use that plugin ourselves.

There is currently no functionality in our application to translate either the filter or the expression tree generated by our package to SQL.  Our use case mostly revolves around using our package against a collection of objects in memory, so it wasn't a priority for us to make SQL related scenarios work outside of what's already supported in the client-side plugins.  That said, a pull-request would be welcome if you're interested in helping us to add that kind of functionality :)  You could look at porting the sql plugin from javascript to c#.

As far as ORMs go, there are an abundance of tutorials and the like around using Entity Framework, a simple search will yield plenty to keep you busy :)

A third option I'll throw out with the caveat that this is only practical for some use cases: You could pull the entire SQL table into memory and execute our package against that materialized collection.  This is what we do, because the SQL queries we use along side our package are expensive enough that it makes more sense to cache the results in memory and filter from there.  This is an atypical scenario however, so only you can judge if it makes sense for you.

**Comment by vickyrathee** [comment]
I should go with porting the SQL plugin form JS to C# because table is too large and will consume lots of memory and time to fetch full data each time. 

But that will take time, and I was looking for package to save time. For now, I will go with stringBuilder something like http://stackoverflow.com/questions/17321281/is-there-a-better-way-to-dynamically-build-an-sql-where-clause-than-by-using-1-1

**Comment by yusufozturk** [comment]
@vickyrathee Did you manage to write it? I need same method so I can filter the results at the database level via Dapper. Thanks!

**Comment by vickyrathee** [comment]
@yusufozturk  No we decided to use Entity framework in list API, and then you can pass the querybuilder IFilterRule easily without writing much of code. 

You can use dapper else where like insert, update and delete operation as that's fast and best performance then EF, but for List (Select many with filter) this is what I found convenient. (Feel free to post here if you found something else working better)

```
public class PagedFilterRequest
    {
        public int offset { get; set; } = 0;
        public int limit { get; set; } = 1000;
        public string sort { get; set; }
        public string order { get; set; }
        public IFilterRule rules { get; set; }
    }
```

```
var query = db.Customers.Where(row => row.customer_id== customer_id);
query = query.BuildQuery(request.rules);

if(string.IsNullOrEmpty(request.order))
   request.order = "asc";

if (!string.IsNullOrEmpty(request.sort) && Helper.PropertyExists<CustomerDTO>(request.sort))
   query = query.OrderBy($"{request.sort} {request.order}");
else
  query = query.OrderBy(o => o.customer_id);

var result = await query.Skip(request.offset).Take(request.limit).ToListAsync();
```

**Comment by yusufozturk** [comment]
@vickyrathee In my case, I had to convert it to query string because we use some heavy queries which is not possible or not very easy via EF.

Here is the minimal version of my method:

`public string ConvertFilterRuleToQuery(FilterRule mainRule, bool child = false)
        {
            if (mainRule.Rules != null && mainRule.Rules.Any())
            {
                List<string> queryList = new List<string>();

                for (int p = 0; p < mainRule.Rules.Count; p++)
                {
                    queryList.Add(convertFilterRuleToQuery(mainRule.Rules[p], true));
                }

                if (child)
                {
                    return "(" + string.Join(" " + mainRule.Condition + " ", queryList) + ")";
                }
                else
                {
                    return string.Join(" " + mainRule.Condition + " ", queryList);
                }
            }

            return mainRule.Field + " " + mainRule.Operator + " " + mainRule.Value;
        }` 

This is for Microsoft SQL.

**Comment by ArgeKumandan** [comment]
@yusufozturk the operator comes with "equal" keyword. And sql doesn't have such an operator. good, but still needs some improvoments. This is exactly what i need. Getting the raw sql from backend via querybuilderjs.

**Comment by AshokAndani** [comment]
Hi @tghamm I've using your project Castle.DynamicLinqQueryBuilder.Samples,  whenever I use the "in" operator I'm not able to choose multiple selections.
![Screenshot (138)](https://user-images.githubusercontent.com/60642640/133273555-8e2ff0c0-1faf-4dee-a4df-a23c94db568b.png)

**Comment by AshokAndani** [comment]
Hi @tghamm  I'm trying to use the Project Castle.DynamicLinqQueryBuilder.Samples, in which we have "in" operator but I'm not able use multiple selections.
<img width="895" alt="Screenshot (138)" src="https://user-images.githubusercontent.com/60642640/133274283-98e593d2-942b-474f-8c96-27a9c327d48d.png">

**Comment by tghamm** [comment]
@AshokAndani that's a misconfiguration of the front-end project jquery-querybuilder.  This library does properly support an "in" with multiple values though.

**Comment by AshokAndani** [comment]
@tghamm  Thanks for replying.
and Yes, I've seen the code and I have not made any changes to project source code still, not able to enter multiple values.
if possible can you check where the misconfiguration is happening because other than "in and not in" operators everything seems fine.
Thanks.

**Comment by AshokAndani** [comment]
Anyone looking to extract SQL query from castle-QueryBuilder can refer this link `<a href="https://stackoverflow.com/questions/37527783/get-sql-code-from-an-entity-framework-core-iqueryablet">Extract sql statement</a>`.
but, you'll still have to make use of entity framework but don't use EF for interacting with Database just use the DbContext and DBSet only to get sql query.
Code-->
class Person{
          public int Id {set; get;}
          public string Name {set; get;}
}

public class DbContextSample : DbContext{
        public DbSet<Person> Persons {set; get;}
}
---not to make any database call with DbContextSample class if you are using anything other than EF for Database interactions.--

--Now Extracting SQL Query from QueryBuilderFilterRule--
public class SQLExtraction{
           private readonly DbContextSample _db;
      public SQLExtraction(DbContextSample dbContext){
            _db=dbContext;
}
public string Test(QueryBuilderFitlerRule FitlerRule){
         var Persons=_db.Persons.Where(x=>x.name.Contains("a")).BuildQuery(FilterRule);
        string SQLQuery=  Persons.ToSql();// this method is a extension method from the link attached above. 
         return SQlQuery;
}

**Comment by AshokAndani** [comment]
Anyone looking to extract SQL query from castle-QueryBuilder can refer this link <a href="https://stackoverflow.com/questions/37527783/get-sql-code-from-an-entity-framework-core-iqueryablet">Extract sql statement</a>.
but, you'll still have to make use of entity framework but don't use EF for interacting with Database just use the DbContext and DBSet only to get sql query.
Code-->
class Person{
public int Id {set; get;}
public string Name {set; get;}
}

public class DbContextSample : DbContext{
public DbSet Persons {set; get;}
}
---not to make any database call with DbContextSample class if you are using anything other than EF for Database interactions.--

--Now Extracting SQL Query from QueryBuilderFilterRule--
public class SQLExtraction{
private readonly DbContextSample _db;
public SQLExtraction(DbContextSample dbContext){
_db=dbContext;
}
public string Test(QueryBuilderFitlerRule FitlerRule){
var Persons=_db.Persons.Where(x=>x.name.Contains("a")).BuildQuery(FilterRule);
string SQLQuery= Persons.ToSql();// this method is a extension method from the link attached above.
return SQlQuery;
}
